# Generated by Django 5.1.4 on 2025-03-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_content_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="title",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
