# Generated by Django 5.1.4 on 2025-03-09 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_content_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
